#include "cardstack.h"

void CardStack::LoadStack()
{
	stack =
	{
		{CARDCOLOR::BLUE, CARDSYMBOL::ONE},
		{CARDCOLOR::BLUE, CARDSYMBOL::TWO},
		{CARDCOLOR::BLUE, CARDSYMBOL::THREE},
		{CARDCOLOR::BLUE, CARDSYMBOL::FOUR},
		{CARDCOLOR::BLUE, CARDSYMBOL::FIVE},
		{CARDCOLOR::BLUE, CARDSYMBOL::SIX},
		{CARDCOLOR::BLUE, CARDSYMBOL::SEVEN},
		{CARDCOLOR::BLUE, CARDSYMBOL::EIGHT},
		{CARDCOLOR::BLUE, CARDSYMBOL::NINE},
		{CARDCOLOR::BLUE, CARDSYMBOL::ZERO},
		{CARDCOLOR::BLUE, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::BLUE, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::BLUE, CARDSYMBOL::REVERSE},
		{CARDCOLOR::BLUE, CARDSYMBOL::REVERSE},
		{CARDCOLOR::BLUE, CARDSYMBOL::SUSPEND},
		{CARDCOLOR::BLUE, CARDSYMBOL::SUSPEND},

		{CARDCOLOR::RED, CARDSYMBOL::ONE},
		{CARDCOLOR::RED, CARDSYMBOL::TWO},
		{CARDCOLOR::RED, CARDSYMBOL::THREE},
		{CARDCOLOR::RED, CARDSYMBOL::FOUR},
		{CARDCOLOR::RED, CARDSYMBOL::FIVE},
		{CARDCOLOR::RED, CARDSYMBOL::SIX},
		{CARDCOLOR::RED, CARDSYMBOL::SEVEN},
		{CARDCOLOR::RED, CARDSYMBOL::EIGHT},
		{CARDCOLOR::RED, CARDSYMBOL::NINE},
		{CARDCOLOR::RED, CARDSYMBOL::ZERO},
		{CARDCOLOR::RED, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::RED, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::RED, CARDSYMBOL::REVERSE},
		{CARDCOLOR::RED, CARDSYMBOL::REVERSE},
		{CARDCOLOR::RED, CARDSYMBOL::SUSPEND},
		{CARDCOLOR::RED, CARDSYMBOL::SUSPEND},

		{CARDCOLOR::YELLOW, CARDSYMBOL::ONE},
		{CARDCOLOR::YELLOW, CARDSYMBOL::TWO},
		{CARDCOLOR::YELLOW, CARDSYMBOL::THREE},
		{CARDCOLOR::YELLOW, CARDSYMBOL::FOUR},
		{CARDCOLOR::YELLOW, CARDSYMBOL::FIVE},
		{CARDCOLOR::YELLOW, CARDSYMBOL::SIX},
		{CARDCOLOR::YELLOW, CARDSYMBOL::SEVEN},
		{CARDCOLOR::YELLOW, CARDSYMBOL::EIGHT},
		{CARDCOLOR::YELLOW, CARDSYMBOL::NINE},
		{CARDCOLOR::YELLOW, CARDSYMBOL::ZERO},
		{CARDCOLOR::YELLOW, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::YELLOW, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::YELLOW, CARDSYMBOL::REVERSE},
		{CARDCOLOR::YELLOW, CARDSYMBOL::REVERSE},
		{CARDCOLOR::YELLOW, CARDSYMBOL::SUSPEND},
		{CARDCOLOR::YELLOW, CARDSYMBOL::SUSPEND},

		{CARDCOLOR::GREEN, CARDSYMBOL::ONE},
		{CARDCOLOR::GREEN, CARDSYMBOL::TWO},
		{CARDCOLOR::GREEN, CARDSYMBOL::THREE},
		{CARDCOLOR::GREEN, CARDSYMBOL::FOUR},
		{CARDCOLOR::GREEN, CARDSYMBOL::FIVE},
		{CARDCOLOR::GREEN, CARDSYMBOL::SIX},
		{CARDCOLOR::GREEN, CARDSYMBOL::SEVEN},
		{CARDCOLOR::GREEN, CARDSYMBOL::EIGHT},
		{CARDCOLOR::GREEN, CARDSYMBOL::NINE},
		{CARDCOLOR::GREEN, CARDSYMBOL::ZERO},
		{CARDCOLOR::GREEN, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::GREEN, CARDSYMBOL::DRAWTWO},
		{CARDCOLOR::GREEN, CARDSYMBOL::REVERSE},
		{CARDCOLOR::GREEN, CARDSYMBOL::REVERSE},
		{CARDCOLOR::GREEN, CARDSYMBOL::SUSPEND},
		{CARDCOLOR::GREEN, CARDSYMBOL::SUSPEND},

		{CARDCOLOR::NONE, CARDSYMBOL::CHANGECOLOR},
		{CARDCOLOR::NONE, CARDSYMBOL::CHANGECOLOR},
		{CARDCOLOR::NONE, CARDSYMBOL::CHANGECOLOR},
		{CARDCOLOR::NONE, CARDSYMBOL::CHANGECOLOR},

		{CARDCOLOR::NONE, CARDSYMBOL::DRAWFOURCHANGECOLOR},
		{CARDCOLOR::NONE, CARDSYMBOL::DRAWFOURCHANGECOLOR},
		{CARDCOLOR::NONE, CARDSYMBOL::DRAWFOURCHANGECOLOR},
		{CARDCOLOR::NONE, CARDSYMBOL::DRAWFOURCHANGECOLOR}
	};
}

std::vector<Card> CardStack::DrawCards(int num)
{
	std::vector<Card> ret{};
	for (size_t i{ 0 }; i < num; ++i)
	{
		ret.push_back(DrawCard());
	}
	return ret;
}

Card CardStack::DrawCard()
{
	auto ret = stack.back();
	stack.pop_back();
	return ret;
}

void CardStack::MixCards()
{
	unsigned seed = std::chrono::system_clock::now().time_since_epoch().count();
	std::shuffle(std::begin(stack), std::end(stack), std::default_random_engine(seed));
}
